apiVersion: v1
kind: Secret
metadata:
  name: demo-consumer-jwt
  namespace: api-security-demo
  labels:
    konghq.com/credential: jwt
type: Opaque
stringData:
  algorithm: HS256
  key: demo-client
  secret: demo-super-secret
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: demo-consumer
  namespace: api-security-demo
  annotations:
    kubernetes.io/ingress.class: kong
username: demo-consumer
credentials:
- demo-consumer-jwt
